### ISSUE TITLE
Don't exit the REPL when there is an error

### ISSUE THREAD

**Issue by ghost** [HiiGHoVuTi/Catrina#1]
Currently, the REPL will immediately exit if there was an error.
```
h ~/Catrina > rina repl --load main.rina
Rina> safvsdcnpkznv
rina: Can't find safvsdcnpkznv
CallStack (from HasCallStack):
  error, called at app/Interpreter/BuiltIn.hs:24:27 in main:Interpreter.BuiltIn
h ~/Catrina 1 > 
```

It should behave like other languages' REPLs in that they do not exit immediately if there is an error with your code.
```
h ~/Catrina > ipython
Python 3.10.1 (main, Dec 18 2021, 23:53:45) [GCC 11.1.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.30.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: raise Exception()
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-1-32c500991385> in <module>
----> 1 raise Exception()

Exception: 

In [2]: 
```

**Comment by HiiGHoVuTi** [comment]
This is only a result of the lack of semantic analysis, this code will not be accepted at all in the future, therefore it won't crash the REPL !
I can consider adding a temporary failsafe in the meantime.

**Comment by HiiGHoVuTi** [comment]
![image](https://user-images.githubusercontent.com/38762417/148833571-ee92a06b-4901-40bd-93e5-ea483a93283d.png)
